name: Auto Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ftp.zulfiqri.com
          username: deployci4@zulfiqri.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          protocol: ftps
          exclude: |
            **/.git*
            **/.github*
            **/tests*
            **/writable/debugbar/*
