name: Auto Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ===============================
      # 1️⃣ DEPLOY PUBLIC (untuk domain)
      # ===============================

      - name: Deploy PUBLIC to public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ftp.zulfiqri.com
          username: deployci4@zulfiqri.com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /public_html/ # tujuan di hosting
          local-dir: ./public/ # folder public di project
          exclude: |
            **/.git*
            **/.github*
            **/vendor/*
            **/writable/*
            **/.env

      # =======================================
      # 2️⃣ DEPLOY CORE APP (ke folder ci4_app)
      # =======================================

      - name: Deploy APP CORE to ci4_app
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ftp.zulfiqri.com
          username: deployci4@zulfiqri.com
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /ci4_app/
          local-dir: ./ # root project VS Code
          exclude: |
            **/.git*
            **/.github*
            **/public/*
            **/vendor/*
            **/writable/*
            **/.env
            spark
            build
